version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "2000:2000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "30:30"

    